apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: urlshortener
data:
  BASE_URL: "http://a062a137ecba74a07834ff5eec2c84c4-a7f1e0f5b0040820.elb.ap-south-1.amazonaws.com"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  GO_SERVICE_URL: "http://go-service:8000"
  NODE_SERVICE_URL: "http://node-service:3000"
  PYTHON_SERVICE_URL: "http://python-service:5000"