apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: urlshortener
type: Opaque
stringData:
  DOCKERHUB_USERNAME: "mdsadidtahsin"
  DOCKERHUB_TOKEN: "dckr_pat_B_9cXvt_GNUk047RcFISUM5aCbc"
  SONAR_TOKEN: "5cda6224cca74014d5a1301be4b8e2d88092a94f"
  AWS_ACCESS_KEY_ID: "AKIAWQ3MELK6KEVJXSKJ"
  AWS_SECRET_ACCESS_KEY: "OaI0HexrJOdrN2TowBsfTdkrcEGq"